const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET,OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

export default {
  async fetch(request) {
    // Handle CORS preflight
    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders });
    }

    const { cf } = request;

    return new Response(
      JSON.stringify(
        {
          explanation:
            "This response is generated by a Cloudflare Worker, which runs per request at the edge.",
          trigger: "HTTP request",
          edge_location: {
            country: cf?.country,
            colo: cf?.colo,
            city: cf?.city,
            timezone: cf?.timezone,
          },
          request: {
            method: request.method,
            url: request.url,
          },
          timestamp: new Date().toISOString(),
        },
        null,
        2
      ),
      {
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  },
};
